server:
  port: 8066

spring:
  application:
    name: metrics
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configserver
  profiles:
    active: dev
# tag::configuration-eureka[]
eureka:  #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8091/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management.security.enabled: false  #<2>
# end::configuration-eureka[]

# tag::configuration-ui-hystrix[]
spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
# end::configuration-ui-hystrix[]

# tag::configuration-ui-turbine[]
spring.boot.admin.turbine:
  clusters: default
  location: turbine  #<1>
# end::configuration-ui-turbine[]

---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}