server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lfvepclr/spring-cloud-learning
          basedir: target/config
          search-paths: config-repo/dev